import JSZip from "jszip";

export interface ZipExportOptions {
  skillName: string;
  skillTitle: string;
  cursorRulesContent: string;
  skillMdContent: string;
  claudeMdContent: string;
  agentsMdContent: string;
  framework: string;
  language: string;
}

/**
 * Builds and triggers download of a complete AI configuration kit in a single .zip archive.
 */
export async function downloadAiKitZip(options: ZipExportOptions): Promise<void> {
  const zip = new JSZip();
  const slug = (options.skillName || "ai-rule").trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-");

  // 1. Cursor rules file
  zip.file(`.cursor/rules/${slug}.mdc`, options.cursorRulesContent);

  // 2. Claude Code Agent Skill
  zip.file(`.claude/skills/${slug}/SKILL.md`, options.skillMdContent);

  // 3. Project Root CLAUDE.md
  zip.file("CLAUDE.md", options.claudeMdContent);

  // 4. Multi-Agent AGENTS.md
  zip.file("AGENTS.md", options.agentsMdContent);

  // 5. Instruction Manual README.md
  const readmeContent = `# ${options.skillTitle || "AI Configuration Suite"}

Generated by **AI Skill Studio** (DevScratchpad) for **${options.framework}** & **${options.language}**.

## Directory Layout & How to Install

### 1. Cursor IDE Rules (.cursor/rules/)
- Copy \`.cursor/rules/${slug}.mdc\` into your repository's \`.cursor/rules/\` folder.
- Cursor will automatically evaluate the glob patterns and inject instructions during agent generation.

### 2. Claude Code Agent Skills (.claude/skills/)
- Project Scope: Copy \`.claude/skills/${slug}/SKILL.md\` into your repo's \`.claude/skills/${slug}/\`.
- Global Scope: Copy into \`~/.claude/skills/${slug}/SKILL.md\` to make it available across all your terminal sessions.

### 3. Project Root Guidelines (CLAUDE.md)
- Copy \`CLAUDE.md\` directly to the root of your project.
- Claude Code and web Claude read this file automatically at the start of every interaction.

### 4. Multi-Agent Directives (AGENTS.md)
- Place \`AGENTS.md\` in your repository root.
- Multi-agent runners (Antigravity, AutoGen, CrewAI) use this to coordinate subagent execution.

---
*Created with privacy-first client-side architecture on DevScratchpad (https://www.devscratchpad.tech/ai-skill-studio).*
`;

  zip.file("README.md", readmeContent);

  // Generate blob and trigger download
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${slug}-ai-suite.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
