import { generateSafeSlug } from "./slugUtils";

export interface ZipExportOptions {
  skillName: string;
  skillTitle: string;
  cursorRulesContent: string;
  skillMdContent: string;
  claudeMdContent: string;
  agentsMdContent: string;
  mcpJsonContent: string;
  windsurfContent?: string;
  copilotContent?: string;
  openaiContent?: string;
  geminiContent?: string;
  cursorignoreContent?: string;
  claudeignoreContent?: string;
  llmsTxtContent?: string;
  architectureMdContent?: string;
  framework: string;
  language: string;
}

/**
 * Builds and triggers download of a complete AI configuration kit in a single .zip archive.
 */
export async function downloadAiKitZip(options: ZipExportOptions): Promise<void> {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  const rawSkillName = options.skillName || "ai-rule";
  const posixSafeSkillName = rawSkillName.replace(/[^a-zA-Z0-9._-]/g, "-");
  const slug = generateSafeSlug(posixSafeSkillName).replace(/[^a-zA-Z0-9._-]/g, "-") || "ai-rule";

  // 1. Cursor rules file
  zip.file(`.cursor/rules/${slug}.mdc`, options.cursorRulesContent);

  // 2. Claude Code Agent Skill
  zip.file(`.claude/skills/${slug}/SKILL.md`, options.skillMdContent);

  // 3. Project Root CLAUDE.md
  zip.file("CLAUDE.md", options.claudeMdContent);

  // 4. Multi-Agent AGENTS.md
  zip.file("AGENTS.md", options.agentsMdContent);

  // 5. MCP Server Configuration (claude.json)
  zip.file("claude.json", options.mcpJsonContent);

  // 6. Windsurf Cascade Rules
  if (options.windsurfContent) {
    zip.file(`.windsurf/rules/${slug}.md`, options.windsurfContent);
  }

  // 7. GitHub Copilot Instructions
  if (options.copilotContent) {
    zip.file(".github/copilot-instructions.md", options.copilotContent);
  }

  // 8. OpenAI Custom Instructions
  if (options.openaiContent) {
    zip.file("prompts/openai-custom-instructions.md", options.openaiContent);
  }

  // 9. Gemini System Prompt
  if (options.geminiContent) {
    zip.file("prompts/gemini-system-instructions.json", options.geminiContent);
  }

  // 10. .cursorignore (Token & Secret Shield)
  if (options.cursorignoreContent) {
    zip.file(".cursorignore", options.cursorignoreContent);
  }

  // 11. .claudeignore (Claude Code Boundary Shield)
  if (options.claudeignoreContent) {
    zip.file(".claudeignore", options.claudeignoreContent);
  }

  // 12. llms.txt (Machine-Readable Codebase Roadmap)
  if (options.llmsTxtContent) {
    zip.file("llms.txt", options.llmsTxtContent);
  }

  // 13. ARCHITECTURE.md (System Invariants Spec)
  if (options.architectureMdContent) {
    zip.file("ARCHITECTURE.md", options.architectureMdContent);
  }

  // 14. Instruction Manual README.md
  const readmeContent = `# ${options.skillTitle || "AI Configuration Suite"}

Generated by **AI Skill Studio** (DevScratchpad) for **${options.framework}** & **${options.language}**.

## Directory Layout & How to Install

### 1. Cursor IDE Rules (.cursor/rules/)
- Copy \`.cursor/rules/${slug}.mdc\` into your repository's \`.cursor/rules/\` folder.
- Cursor will automatically evaluate the glob patterns and inject instructions during agent generation.

### 2. Cursor Token & Secret Shield (.cursorignore)
- Place \`.cursorignore\` in your repository root.
- Masks API credentials and excludes build caches / bulky lockfiles, saving 50k+ context tokens.

### 3. Claude Code Agent Skills (.claude/skills/)
- Project Scope: Copy \`.claude/skills/${slug}/SKILL.md\` into your repo's \`.claude/skills/${slug}/\`.
- Global Scope: Copy into \`~/.claude/skills/${slug}/SKILL.md\` to make it available across all your terminal sessions.

### 4. Claude Code Privacy Shield (.claudeignore)
- Place \`.claudeignore\` in your repository root to restrict Claude Code terminal inspection.

### 5. Project Root Guidelines (CLAUDE.md)
- Copy \`CLAUDE.md\` directly to the root of your project.
- Claude Code and web Claude read this file automatically at the start of every interaction.

### 6. Multi-Agent Directives (AGENTS.md)
- Place \`AGENTS.md\` in your repository root.
- Multi-agent runners (Antigravity, AutoGen, CrewAI) use this to coordinate subagent execution.

### 7. Machine-Readable Codebase Roadmap (llms.txt)
- Place \`llms.txt\` in your repository root. Provides LLMs and search engines with a clean, concise index.

### 8. System Architecture Blueprint (ARCHITECTURE.md)
- Place \`ARCHITECTURE.md\` in your repository root. Establishes non-negotiable data flow and state invariants.

### 9. Windsurf Cascade Rules (.windsurf/rules/)
- Copy \`.windsurf/rules/${slug}.md\` into your repository's \`.windsurf/rules/\` folder.

### 10. GitHub Copilot Instructions (.github/)
- Copy \`.github/copilot-instructions.md\` into your repository's \`.github/\` folder.

### 11. MCP Server Configuration (claude.json)
- Claude Code: Place \`claude.json\` in your project root or merge its \`mcpServers\` block into \`.claude/mcp.json\`.
- Claude Desktop: Merge the \`mcpServers\` object into your \`claude_desktop_config.json\` file.

### 12. OpenAI & Gemini System Prompts (prompts/)
- Contains ready-to-paste system prompts for ChatGPT Custom GPTs and Google Gemini API assistants.

---
*Created with privacy-first client-side architecture on DevScratchpad (https://www.devscratchpad.tech/ai-skill-studio).*
`;

  zip.file("README.md", readmeContent);

  // Generate blob and trigger download
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const downloadFileName = `${slug}-ai-suite.zip`.replace(/[^a-zA-Z0-9._-]/g, "-");
  link.download = downloadFileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
