import { LearningTrack, QuickCheatItem } from "./types";

export const LEARNING_TRACKS: LearningTrack[] = [
  {
    id: "security-cryptography",
    title: "Application Security & Cryptography Playbook",
    category: "Security & Cryptography",
    description: "Deep dive into RFC standards, token security, one-way password hashing, public-key infrastructure, and offline crypto.",
    badge: "Most Popular",
    iconName: "ShieldCheck",
    estimatedTime: "45 mins",
    level: "Intermediate",
    guideSlugs: [
      "jwt-token-decode-guide",
      "password-hashing-bcrypt-argon2",
      "x509-certificate-decoder-guide",
      "ssh-key-generator-guide",
      "openssl-x509-devops-cheat-sheet",
      "base64-inspector-guide",
    ],
  },
  {
    id: "devops-automation",
    title: "DevOps, Linux & Cloud Automation Track",
    category: "DevOps & Cloud",
    description: "Essential cheat sheets and syntax guides for cron jobs, regular expressions, network boundaries, and server maintenance.",
    badge: "Essential",
    iconName: "Terminal",
    estimatedTime: "35 mins",
    level: "Beginner",
    guideSlugs: [
      "cron-expression-cheat-sheet",
      "regex-cheat-sheet-recipes",
      "modern-http-status-codes-reference",
      "uuid-v4-v5-v7-explained",
      "json-formatter-privacy-backed-developer-tools",
    ],
  },
  {
    id: "api-data-mastery",
    title: "API Translation & Web Data Mastery Track",
    category: "API & Automation",
    description: "Master modern API workflows: converting cURL commands to Python/Go/Fetch, translating JSON to TypeScript & Zod schemas.",
    badge: "Practical",
    iconName: "Cpu",
    estimatedTime: "40 mins",
    level: "Beginner",
    guideSlugs: [
      "convert-curl-to-python",
      "convert-curl-to-fetch-axios",
      "curl-to-go-javascript-python-code-generators",
      "json-to-typescript-zod-schema-guide",
      "yaml-to-json-conversion-developers",
    ],
  },
];

export const QUICK_CHEATS: QuickCheatItem[] = [
  {
    id: "cron-15",
    title: "Cron Every 15 Minutes",
    syntax: "*/15 * * * *",
    description: "Runs at minute 0, 15, 30, and 45 of every hour.",
    category: "DevOps",
    toolSlug: "cron",
  },
  {
    id: "ssh-ed25519",
    title: "Generate Ed25519 SSH Key",
    syntax: 'ssh-keygen -t ed25519 -C "admin@company.com"',
    description: "Modern, high-performance cryptographic SSH keypair standard.",
    category: "Security",
    toolSlug: "ssh-key-generator",
  },
  {
    id: "jwt-bash",
    title: "Decode JWT in Terminal",
    syntax: "echo $JWT | cut -d. -f2 | base64 -d 2>/dev/null | jq .",
    description: "Quickly inspect claims without leaving the terminal shell.",
    category: "Security",
    toolSlug: "jwt",
  },
  {
    id: "curl-python-post",
    title: "Python requests JSON POST",
    syntax: "requests.post(url, json=payload, headers={'Authorization': f'Bearer {token}'})",
    description: "Native JSON serialization with automated Content-Type header.",
    category: "API",
    toolSlug: "curl-to-python",
  },
  {
    id: "openssl-inspect",
    title: "Inspect X.509 Certificate",
    syntax: "openssl x509 -in cert.pem -text -noout",
    description: "Extract validity dates, SANs, and issuer details from PEM.",
    category: "Security",
    toolSlug: "cert-decoder",
  },
  {
    id: "regex-email",
    title: "RFC Email Regex Match",
    syntax: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
    description: "Standard email format pattern validation.",
    category: "Syntax",
    toolSlug: "regex",
  },
  {
    id: "docker-cleanup",
    title: "Weekly Docker Prune Crontab",
    syntax: "0 3 * * 0 /usr/bin/docker system prune -af > /dev/null 2>&1",
    description: "Purge dangling images, containers, and volumes every Sunday at 3 AM.",
    category: "DevOps",
    toolSlug: "cron",
  },
  {
    id: "uuid-v4-node",
    title: "Native Node.js UUID v4",
    syntax: "crypto.randomUUID()",
    description: "Zero-dependency cryptographically secure v4 UUID generator.",
    category: "Data",
    toolSlug: "uuid-generator",
  },
];
